FROM mcr.microsoft.com/playwright:v1.34.0-jammy
USER root 
RUN mkdir /tests 
COPY . /tests               
WORKDIR /tests 
## Install Playwright dependencies 
RUN npm install 
## Install dependencies 
RUN npx @playwright/test install 
## Run Tests 
# RUN npx playwright test --reporter=list 
RUN npx playwright install-deps 
RUN npx playwright test
